### ISSUE TITLE
Extra files under version control

### ISSUE THREAD

**Issue by mkwork** [drewpts/LPROJ-main#1]
https://github.com/drewpts/LPROJ-main/blob/master/lproj4.pro.user

.gitignore missed

**Comment by drewpts** [comment]
done

2015-01-25 22:07 GMT+02:00 Maxim Kot notifications@github.com:

**Comment by mkwork** [comment]
Press close issue, and comment there next time :)

**Comment by mkwork** [comment]
Like this

**Comment by drewpts** [comment]
Yep

2015-01-26 12:31 GMT+02:00 Maxim Kot notifications@github.com:
