### ISSUE TITLE
In terms of LPROJ-28 task.

### ISSUE THREAD

**Issue by drewpts** [drewpts/LPROJ-main#100]
There are headers which all need to be included in cmake config as headers of PluginManager's interface:
$QTC_SOURCE/src/libs/extensionsystem/extensionsystem_global.h
$QTC_SOURCE/src/libs/aggregation/aggregate.h
QObject
QStringList

**Comment by mkwork** [comment]
Ok. So there two folders of qtc and two pure Qt's depencies.

Sounds good and quite easy.
Please take a look documented way to use Qt from CMake. 
And inscribe Qtc headers inclusion as an FindQtc.cmake script

**Comment by mkwork** [comment]
Some notes: when you tell about some external task here on github, please make a link.
And why you just don't put it at yourtrack?

**Comment by drewpts** [comment]
Ok, next time I'll make it right way :))

2015-07-26 19:56 GMT+03:00 Maxim Kot notifications@github.com:
