### ISSUE TITLE
Remove stale qt-json submodule from code base

### ISSUE THREAD

**Issue by mkwork** [drewpts/LPROJ-main#18]

**Comment by drewpts** [comment]
fxd

**Comment by mkwork** [comment]
And where is pull request?

**Comment by drewpts** [comment]
I haven't yet fixed other issues marked by you.

**Comment by mkwork** [comment]
Ok, next time, before close issues on gh, please put a link for a merge request, please
Also, you can automatically link such merge request to issue, if in commit message you will write Fixes "#issue-number"

You can touch it close there https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by mkwork** [comment]
Still presented in develop branch
Please investigate is it github issue or you missing something.
