### ISSUE TITLE
Undocumented interface

### ISSUE THREAD

**Issue by mkwork** [drewpts/LPROJ-main#35]
https://github.com/drewpts/LPROJ-main/blob/LPROJ-12__RE_working_on_subprojects_support/src/libproject/libproject.h#L33

Interface methods undocumented.

**Comment by drewpts** [comment]
Sorry for such mess. I'll report you when it will be fixed.

**Comment by mkwork** [comment]
We had a deal, that such issues will be fixed in maximal priority :)

**Comment by drewpts** [comment]
@mkwork 
Can you close this issue?

**Comment by drewpts** [comment]
Done.
