### ISSUE TITLE
Implement regex checking

### ISSUE THREAD

**Issue by drewpts** [drewpts/LPROJ-main#41]
This is necessary when API checking project file content. Especially on "subprojects" key.

**Comment by mkwork** [comment]
What is necessary?

**Comment by drewpts** [comment]
@mkwork necessary checking correctness of paths. Or will it be perform by some filesystem api?

**Comment by mkwork** [comment]
It should be passed as is to underlying level. If path is wrong, fs api report error. So you should perform such checks at yours level.

**Comment by mkwork** [comment]
So issue is closed :)
