### ISSUE TITLE
Move library includes

### ISSUE THREAD

**Issue by mkwork** [drewpts/LPROJ-main#63]
libproject's includes should be moved to <root_directory>/include/libproject/
In library code and in any other code them should be used like below:

``` cpp
#include <libproject/libproject.h>
#include <libproject/project_error.h>
```

**Comment by drewpts** [comment]
@mkwork 
I guess I need to put folder **include/libproject** in **src**. Am I right?

**Comment by mkwork** [comment]
Nope, just in the root folder.

**Comment by mkwork** [comment]
When you seen any not qualified path, please interpret it just like a path relative to the root folder.

**Comment by mkwork** [comment]
And you already know where should be moved code related to includes installation :)

**Comment by drewpts** [comment]
@mkwork 
Accordingly to all what you just said is necessary line:
`${PROJECT_SOURCE_DIR}/src/include`
at root CMakeLists.txt?

**Comment by mkwork** [comment]
include/CMakeListst.txt
install(DIRECTORY) or install(PUBLIC_HEADER) in combination with file(GLOB) can be used.

**Comment by drewpts** [comment]
@mkwork I can't clearly understood you. :) What purpose of new **CMakeLists.txt** nested in folder **include**?

I've used `FILES_MATCHING PATTERN` instead of `GLOB`. Do you mind?

**Comment by mkwork** [comment]
@drewpts, you have includes directory. You need to install headers. So where should be code, which serves this needs?

Right, much close to sources, which it serving.

**Comment by drewpts** [comment]
@mkwork 
yes, I understood your point: if this stuff will be perform actions from directory then there is no need in `FILES_MATCHING PATTERN` but in `GLOB` is.

**Comment by 4e7** [comment]
Who knew any "delegat" methods? May be he means that? 😅

Отправлено с моего Windows Phone
________________________________
От: drewpts<mailto:notifications@github.com>
Отправлено: ‎07.‎05.‎2015 22:10
Кому: drewpts/LPROJ-main<mailto:LPROJ-main@noreply.github.com>
Тема: Re: [LPROJ-main] Move library includes (#63)

@mkwork
yes, I understood your point: if this stuff will be preform actions from directory then there is no need in ``FILES_MATCHING PATTERN`` but in ``GLOB`` is.

---

**Comment by mkwork** [comment]
@4e7 what a fck?:) What are you talking about?
If you want to chat, just go jabber or hangouts, you have whole mine contacts;)

**P.s.** i'm really misunderstood, what did you mean when talk about **delegat**e methods.

**Comment by 4e7** [comment]
https://msdn.microsoft.com/ru-ru/library/ms173171.aspx
Я вот о чем "ебаут" могу же я вас, наконец, носпамить, пока не в проекте...

Отправлено с моего Windows Phone
________________________________
От: Maxim Kot<mailto:notifications@github.com>
Отправлено: ‎08.‎05.‎2015 1:03
Кому: drewpts/LPROJ-main<mailto:LPROJ-main@noreply.github.com>
Копия: 4e7<mailto:mc_jest@live.ru>
Тема: Re: [LPROJ-main] Move library includes (#63)

@4e7 what a fck?:) What are you talking about?
If you want to chat, just go jabber or hangouts, you have whole mine contacts;)

**P.s.** i'm really misunderstood, what did you mean when talk about **delegat**e methods.

---

**Comment by mkwork** [comment]
@4e7, че к чему ?
Проект на c++ а не на c#.
Речь в этой баге - идёт вообще про систему сборки.
Это обсуждение баги, а не чат на тему чего то там.
Наспамить ты кончено можешь, но зачем?
